#!/bin/bash
star_wars_script="
A long time ago in a galaxy far, far away...
It is a period of civil war.
Rebel spaceships, striking from a hidden base, have won their first victory against the evil Galactic Empire.
During the battle, Rebel spies managed to steal secret plans to the Empire's ultimate weapon, the Death Star..."

echo "$star_wars_script"
